//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegexUp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RegexUp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A current group name must be specified for the balance group..
        /// </summary>
        internal static string CurrentGroupNameBlank {
            get {
                return ResourceManager.GetString("CurrentGroupNameBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capture group number must be 1 or greater..
        /// </summary>
        internal static string InvalidBackreferenceNumber {
            get {
                return ResourceManager.GetString("InvalidBackreferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capture group name is invalid..
        /// </summary>
        internal static string InvalidCaptureGroupName {
            get {
                return ResourceManager.GetString("InvalidCaptureGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An inline comment cannot contain a right parenthesis..
        /// </summary>
        internal static string InvalidComment {
            get {
                return ResourceManager.GetString("InvalidComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A control character must be a letter between A and Z..
        /// </summary>
        internal static string InvalidControlCharacter {
            get {
                return ResourceManager.GetString("InvalidControlCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounted an unknown regex option..
        /// </summary>
        internal static string InvalidGroupOptions {
            get {
                return ResourceManager.GetString("InvalidGroupOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hexidecimal code must be 2 characters..
        /// </summary>
        internal static string InvalidHexidecimalCode {
            get {
                return ResourceManager.GetString("InvalidHexidecimalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum value must be less than or equal to the maximum value..
        /// </summary>
        internal static string InvalidMinMax {
            get {
                return ResourceManager.GetString("InvalidMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An octal code cannot exceed 3 characters..
        /// </summary>
        internal static string InvalidOctalCode {
            get {
                return ResourceManager.GetString("InvalidOctalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered an invalid character range..
        /// </summary>
        internal static string InvalidRange {
            get {
                return ResourceManager.GetString("InvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unicode code must be 4 characters..
        /// </summary>
        internal static string InvalidUnicodeCode {
            get {
                return ResourceManager.GetString("InvalidUnicodeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A previous group name must be specified for the balance group..
        /// </summary>
        internal static string PreviousGroupNameBlank {
            get {
                return ResourceManager.GetString("PreviousGroupNameBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiline and single line mode cannot be specified at the same time..
        /// </summary>
        internal static string SingleAndMultilineMode {
            get {
                return ResourceManager.GetString("SingleAndMultilineMode", resourceCulture);
            }
        }
    }
}
